<Project Sdk="Microsoft.NET.Sdk">

  <!--
    Capa de Infraestructura: unica capa que conoce tecnologias concretas de
    persistencia y seguridad (Entity Framework Core, archivos de texto plano,
    JWT, hashing de contrasenas).
  -->
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="8.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.10" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="8.0.2" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.2" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="8.0.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.1.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SB.API_SB.Application\SB.API_SB.Application.csproj" />
    <ProjectReference Include="..\SB.API_SB.Domain\SB.API_SB.Domain.csproj" />
  </ItemGroup>

</Project>
